In [0]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
from sklearn.metrics.pairwise import cosine_similarity

In [0]:
# URL for BERT models
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

# instantiate the BERT models
bert_preprocess_model = hub.KerasLayer(preprocess_url)
bert_model = hub.KerasLayer(encoder_url)

In [0]:
# sentences to be compared
key_phrases = ['he is happy', 'he is sad']

# preprocess the sentences
text_preprocessed = bert_preprocess_model(key_phrases)
text_preprocessed.keys()

Out[48]: dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [0]:
# generate sentence embeddings using BERT
bert_results = bert_model(text_preprocessed)
bert_results.keys()

Out[49]: dict_keys(['default', 'pooled_output', 'encoder_outputs', 'sequence_output'])

In [0]:
sentence_embeddings = bert_results['pooled_output']
sentence_embeddings

Out[50]: <tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.91522634, -0.37087008, -0.5788093 , ..., -0.10418781,
 -0.6424429 , 0.9235477 ],
 [-0.87600935, -0.38720202, -0.5220287 , ..., 0.03788602,
 -0.63824284, 0.91502124]], dtype=float32)>

In [0]:
# calculate the cosine similarity between the sentences
cosine_similarity([sentence_embeddings[0]], [sentence_embeddings[1]])

Out[51]: array([[0.99393636]], dtype=float32)